<?
$aMenuLinks = Array(
    Array(
        "Отзывы",
        "/company/reviews/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Партнеры",
        "/company/partners/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Реквизиты",
        "/company/requisites/",
        Array(),
        Array(),
        ""
    ),
	Array(
        "Персонал",
        "/company/staff/",
        Array(),
        Array(),
        ""
    )
);
?>